### ISSUE TITLE
获取通知信息时出错

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#100]
获取通知信息时出错。

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/weibo.py", line 142, in _http_call
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.2/urllib/request.py", line 138, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 375, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 487, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 413, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 495, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeHack.py", line 20, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/local/lib/python3/dist-packages/WeCase/WTimer.py", line 24, in run
    self.run_function()
  File "/usr/local/lib/python3/dist-packages/WeCase/WeCaseWindow.py", line 458, in show_notify
    reminds = self.get_remind(self.uid())
  File "/usr/local/lib/python3/dist-packages/WeCase/WeCaseWindow.py", line 443, in get_remind
    reminds = self.client.remind.unread_count.get(uid=uid)
  File "/usr/local/lib/python3/dist-packages/WeCase/weibos/client.py", line 40, in __call__
    return super(_UBExecutable, self).__call__(**kw)
  File "/usr/local/lib/python3.2/dist-packages/weibo.py", line 276, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/local/lib/python3.2/dist-packages/weibo.py", line 154, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo.APIError: APIError: 21321: applications over the unaudited use restrictions!, request: /2/remind/unread_count.json
```

**Comment by biergaizi** [comment]
进行别的操作会出错吗？目测是超过 API 次数上限或者渣浪的判断错误。偶尔会这样。

**Comment by cthbleachbit** [comment]
把WeCase最小化了，不知道过了多久就弹窗报错了

**Comment by biergaizi** [comment]
你应该能读懂这个错误信息，这是在检查未读信息数量时 API 抛出没权限的异常。

**Comment by cthbleachbit** [comment]
All right then.

**Comment by Garfield550** [comment]
为何问题这么多....

**Comment by biergaizi** [comment]
因为是渣浪。

**Comment by cthbleachbit** [comment]
黑的漂亮。。。话说这是渣浪进行限制的表现么

**Comment by biergaizi** [comment]
应该不是，只是系统太渣，不稳定罢了。

**Comment by biergaizi** [comment]
恩，确实，是渣浪随机抛出的错误……

**Comment by biergaizi** [comment]
这个错误的定义是：

```
21321   Applications over the unaudited use restrictions    未审核的应用使用人数超过限制
```

显然是系统没事乱报错。

**Comment by biergaizi** [comment]
Fixed in 6d457d6.
