### ISSUE TITLE
不支持在 Cygwin 下打开图片

### ISSUE THREAD

**Issue by senseab** [WeCase/WeCase#103]
错误窗口显示

```
Oops, there is an unexpected error,
Please report it at https://github.com/WeCase/WeCase/issues

Traceback (most recent call last):
  File "/home/tonychyi/wecase-cygwin/lib/python3.2/site-packages/WeCase/WeHack.py", line 20, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tonychyi/wecase-cygwin/lib/python3.2/site-packages/WeCase/WeHack.py", line 56, in start
    assert False
AssertionError
```

**Comment by biergaizi** [comment]
话说，Cygwin 下有 `xdg-open` 或等效工具吗？

**Comment by biergaizi** [comment]
Fixed in c044b24.
