### ISSUE TITLE
OSX 测试报告

### ISSUE THREAD

**Issue by Artoria2e5** [WeCase/WeCase#110]
ISSUE:
无法加载打开大图，然而相应目录下的jpg确实存在。

system info:

``` bash
# uname -a
Darwin applematoMacBook-Pro.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64 #Actually Mac OS X 10.7.5
# python --version
Python 3.3.3
# echo $PATH
/opt/local/Library/Frameworks/Python.framework/Versions/3.3/bin:/mono/bin:/usr/X11/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
```

modified wecase bash

``` bash
#!/bin/bash

for py in `whereis python3 | sed 's/^python: //'`
do
    version=`$py -V 2>&1`
    if [[ "$version" == *"Python 3"* ]]; then
        python3=$py
        break
    fi
done

if [ "$python3" == "" ]; then
    exit 1;
fi

exec $python3 /WeCase/build3/libexec/wecase.py wecase
```

modified pyuic4

``` bash
#!/bin/sh
exec arch -i386 pythonw3.3 /opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/PyQt4/uic/pyuic.py ${1+"$@"}
if expand("%") == ""|browse confirm w|else|confirm w|endif
# orignally -i386 x86_64,however returned "Arch: Can't find X86_64 in path"
```

log

```
PasteBoard: Error creating pasteboard: com.apple.pasteboard.clipboard [-4960]
PasteBoard: Error creating pasteboard: com.apple.pasteboard.find [-4960]
0:50: execution error: An error of type -10810 has occurred. (-10810)
70:78: execution error: An error of type -10810 has occurred. (-10810)
69:77: execution error: An error of type -10810 has occurred. (-10810)
root        : ERROR    苍天啊，大地啊！这个不明错误怎么就发生了呢，
请去 <http://bugs.wecase.org/> 报告该问题

Traceback (most recent call last):
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 146, in setPassword
    self.txt_Password.setText(self.passwd[username])
KeyError: 'arthur200126@yeah.net:q'


Traceback (most recent call last):
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 146, in setPassword
    self.txt_Password.setText(self.passwd[username])
KeyError: 'arthur200126@yeah.net:q'
root        : ERROR    苍天啊，大地啊！这个不明错误怎么就发生了呢，
请去 <http://bugs.wecase.org/> 报告该问题

Traceback (most recent call last):
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 83, in checkLogin
    self.accept()
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 55, in accept
    LoginInfo().add_account(self.username)
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginInfo.py", line 43, in add_account
    f.write("%s %d %s\n" % (account, os.getpid(), argv[1]))
IndexError: list index out of range

Traceback (most recent call last):
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 83, in checkLogin
    self.accept()
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 55, in accept
    LoginInfo().add_account(self.username)
  File "/WeCase/build3/lib/python3.3/site-packages/WeCase/LoginInfo.py", line 43, in add_account
    f.write("%s %d %s\n" % (account, os.getpid(), argv[1]))
IndexError: list index out of range
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_63918611jw1edoyb7q8qgj20b607fgn8.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_756a2689tw1edm6gjq13aj20c82huaud.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_756a2689tw1edm6gjq13aj20c82huaud.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_756a2689tw1edm6gjq13aj20c82huaud.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2

797250640/large_756a2689tw1edm6gjq13aj20c82huaud.jpg.
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_756a2689tw1edm6gjq13aj20c82huaud.jpg.
2014-02-19 20:30:56.059 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[157.000000,18.000000] offset [0.000000,0.000000] glID:3, context:0x7feab600fb90)
2014-02-19 20:30:56.060 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[48.000000,18.000000] offset [362.000000,0.000000] glID:3, context:0x7feab600fb90)
2014-02-19 20:30:56.061 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[44.000000,18.000000] offset [410.000000,0.000000] glID:3, context:0x7feab600fb90)
2014-02-19 20:30:56.061 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[89.000000,18.000000] offset [454.000000,0.000000] glID:3, context:0x7feab600fb90)
2014-02-19 20:30:56.061 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[53.000000,18.000000] offset [543.000000,0.000000] glID:3, context:0x7feab600fb90)
2014-02-19 20:30:56.061 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[45.000000,18.000000] offset [596.000000,0.000000] glID:3, context:0x7feab600fb90)
2014-02-19 20:30:56.063 Python[67179:1607] --ImageKit Error: IKGLTextCache::createTexture glerror 506 before creating texture
2014-02-19 20:30:56.063 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[59.000000,16.000000] offset [37.000000,0.000000] glID:6, context:0x7feab600fb90)
2014-02-19 20:30:56.066 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[101.000000,16.000000] offset [96.000000,0.000000] glID:6, context:0x7feab600fb90)
2014-02-19 20:30:56.083 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[66.000000,16.000000] offset [197.000000,0.000000] glID:6, context:0x7feab600fb90)
2014-02-19 20:30:56.083 Python[67179:1607] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 506 (subSize=[72.000000,16.000000] offset [263.000000,0.000000] glID:6, context:0x7feab600fb90)
2014-02-19 20:30:56.084 Python[67179:1607] --ImageKit Error: error before reading pixels: 506
2014-02-19 20:30:56.084 Python[67179:1607] --ImageKit Error: error after reading pixels: 506
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_a6baa850jw1edoyufpwqpj21400p0wq9.jpg.
0:53: execution error: An error of type -10810 has occurred. (-10810)
70:78: execution error: An error of type -10810 has occurred. (-10810)
69:77: execution error: An error of type -10810 has occurred. (-10810)

LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_ea088c90tw1ednuoewptzj20wed7zu0x.jpg.
```

**Comment by biergaizi** [comment]
目测可以给 Qt 报告很多 Bugs 了……

**Comment by biergaizi** [comment]
十分感谢你的测试。

**Comment by biergaizi** [comment]
```
KeyError: 'arthur200126@yeah.net:q'
```

Vim 党暴露了吧，哈哈哈。这个 Bug 是 #107，已经修复了。其它的 Bugs 应该都是新的。

**Comment by biergaizi** [comment]
```
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
```

这个可能是因为你的系统打开了太多文件或者太多进程导致的。这里有几个参考。

http://www.finetunedmac.com/forums/ubbthreads.php?ubb=showflat&Number=25369
http://www.thexlab.com/faqs/error-10810.html

你试试？

**Comment by Garfield550** [comment]
2333

-----原始邮件-----
发件人: "Tom Li" notifications@github.com
发送时间: ‎2014/‎2/‎21 12:16
收件人: "WeCase/WeCase" WeCase@noreply.github.com
主题: Re: [WeCase] OSX 测试报告 (#110)

```
LSOpenURLsWithRole() failed with error -10810 for the file /var/root/.cache/wecase/2797250640/large_9e35e64fgw1edlp73i0taj20te0m2ach.jpg.
```

这个可能是因为你的系统打开了太多文件或者太多进程导致的。这里有几个参考。

http://www.finetunedmac.com/forums/ubbthreads.php?ubb=showflat&Number=25369
http://www.thexlab.com/faqs/error-10810.html

你试试？

---

**Comment by Artoria2e5** [comment]
额，我现在基本算是回来了吧
前几天一怒之下rm -rf了MacPorts安装的prefix`/opt/local`，清理干净装回来…………
登陆框照样挤得没法看，还是去QtCreator随便拉了几下修一下
然后又是喜闻乐见的不影响登陆：

```
Version: WeCase 0.06-beta5-2456d12

Traceback (most recent call last):
  File "/WeCase/destr/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 83, in checkLogin
    self.accept()
  File "/WeCase/destr/lib/python3.3/site-packages/WeCase/LoginWindow.py", line 55, in accept
    LoginInfo().add_account(self.username)
  File "/WeCase/destr/lib/python3.3/site-packages/WeCase/LoginInfo.py", line 43, in add_account
    f.write("%s %d %s\n" % (account, os.getpid(), argv[1]))
IndexError: list index out of range
---[ end trace 0x107fad410 ]---
```

照样是登陆框不消失关掉就好
点击看大图正确调用了“预览”程序，不过由于我现在作为root运行，外部预览程序的普通账户不能
设置里面查看缓存文件也是一个情况
read这些文件……（暴露root敢死队
其他的ui还是没什么特别的……最左边一行照样（上下方向）居中什么的
CPU占用什么的我还是先装个htop再来看吧233
。
然后……这个客户端有查看特定分组的设计吗……

**Comment by Artoria2e5** [comment]
还有关于vim党的……目前我纯属vim当nano用，不过MacVim封装了各种操作用起来就舒服多了hhh（问题是app里面没有包含Mac的图形化提示窗sudo，或者干脆说没有sudo……
然后我都是777/666处理某些我懒得进终端的东西的……能点鼠标是一件幸福的事hhh

**Comment by Artoria2e5** [comment]
还有……目前我的`python`对应py27，`python3`对应py33……所以某个bash没用……

**Comment by biergaizi** [comment]
收到。看来 argv 的传参有些平台上确实问题很大啊，回头改一下……

**Comment by Artoria2e5** [comment]
标准用户测试过了，不过照样是`python3 wecase.py`那么开的……
工作正常，除了UI过于“紧凑”……已经用Qt Designer重新拉了一下（某些大小是Qt自己找了个合适的……），等会再make……

**Comment by Artoria2e5** [comment]
倒是标准用户报了一系列64整数由于数字过大转不到32位的Warning……有空再贴……

**Comment by biergaizi** [comment]
python3 wecase.py 是违规操作。一定要传递一个 wecase 的参数。

python3 wecase.py wecase

**Comment by Artoria2e5** [comment]
瞬间就解决了几乎所有的问题……好吧

**Comment by biergaizi** [comment]
`dev-0.06` 分支更新了，这回也不需要再传递 `wecase` 的参数了，请测试。
