### ISSUE TITLE
Ubuntu 14.04下找不到sip组件

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#120]
```
Traceback (most recent call last):
  File "/usr/local/libexec/wecase.py", line 14, in <module>
    import sip
ImportError: No module named 'sip'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/libexec/wecase.py", line 14, in <module>
    import sip
ImportError: No module named 'sip'
```

由 olinlinlino@gmail.com 反应
环境为ubuntu 14.04且已安装`python3-sip`

**Comment by biergaizi** [comment]
让它用 

```
which python3  # 告诉我输出
python3 /usr/local/libexec/wecase.py # 能否运行
```

**Comment by cthbleachbit** [comment]
输入后弹出一个信息框口

里面内容是：dbus-python 或 notify2 未找到。通知将被禁用。

关掉该窗口后出现登陆框，同时出现一个“未知错误”的窗口

里面内容是

```

苍天啊，大地啊！这个不明错误怎么就发生了呢，

Please report it to <http://bugs.wecase.org/>

------------[ cut here ]------------


Version: WeCase 0.06-beta5-2456d12-dirty


Traceback (most recent call last):

File "/usr/local/lib/python3.4/site-packages/WeCase/LoginWindow.py", line 83, in checkLogin

self.accept()

File "/usr/local/lib/python3.4/site-packages/WeCase/LoginWindow.py", line 55, in accept

LoginInfo().add_account(self.username)

File "/usr/local/lib/python3.4/site-packages/WeCase/LoginInfo.py", line 43, in add_account

f.write("%s %d %s\n" % (account, os.getpid(), argv[1]))

IndexError: list index out of range

---[ end trace 0x7fce9047f728 ]---

```

然后关掉弹框后可以正常登陆账户使用wecase了。

```

-> % python3 /usr/local/libexec/wecase.py

root        : ERROR    苍天啊，大地啊！这个不明错误怎么就发生了呢，

Please report it to <http://bugs.wecase.org/>

------------[ cut here ]------------


Version: WeCase 0.06-beta5-2456d12-dirty


Traceback (most recent call last):

  File "/usr/local/lib/python3.4/site-packages/WeCase/LoginWindow.py", line 83, in checkLogin

    self.accept()

  File "/usr/local/lib/python3.4/site-packages/WeCase/LoginWindow.py", line 55, in accept

    LoginInfo().add_account(self.username)

  File "/usr/local/lib/python3.4/site-packages/WeCase/LoginInfo.py", line 43, in add_account

    f.write("%s %d %s\n" % (account, os.getpid(), argv[1]))

IndexError: list index out of range

---[ end trace 0x7fce9047f728 ]---

Traceback (most recent call last):

  File "/usr/local/lib/python3.4/site-packages/WeCase/LoginWindow.py", line 83, in checkLogin

    self.accept()

  File "/usr/local/lib/python3.4/site-packages/WeCase/LoginWindow.py", line 55, in accept

    LoginInfo().add_account(self.username)

  File "/usr/local/lib/python3.4/site-packages/WeCase/LoginInfo.py", line 43, in add_account

    f.write("%s %d %s\n" % (account, os.getpid(), argv[1]))

IndexError: list index out of range
```

最后

```

which python3

/usr/bin/python3

```

**Comment by biergaizi** [comment]
他用的是旧版本，因此需要传递一个参数才能正常运行。

```
python3 /usr/local/libexec/wecase.py wecase
```

Q & A 结束。

**Comment by biergaizi** [comment]
另外这的确可以算是一个 Bug，启动脚本不太完善。

**Comment by biergaizi** [comment]
启动脚本问题，已开 Issue #122.
