### ISSUE TITLE
@ 自动补全功能在判断何时需要补全时存在问题

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#123]
```
------------[ cut here ]------------

Version: WeCase 0.06-beta5-unknown

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WCompleteLineEdit.py", line 143, in mouseCompleteText
    text = self.getNewText(self.selectedText(), index.data())
  File "/usr/local/lib/python3/dist-packages/WeCase/WCompleteLineEdit.py", line 168, in getNewText
    return original_text[:pos] + new_text + self.separator
UnboundLocalError: local variable 'pos' referenced before assignment
---[ end trace 0xb53a2fc ]---
```

重现步骤：

先输入`@`
然后把`@`去掉
这时进行输入用户列表仍然会弹出，并且如果点击任意用户就会报错

**Comment by biergaizi** [comment]
干得漂亮！

**Comment by biergaizi** [comment]
修复这个 Bug 之前，我先做了两项重构
- 6f92067: WCompleteLineEdit: refactor and fix needComplete()
  
  这项重构解决了在文本框被清空时，依然会进行补全的问题。因此你的重现方法无法在空文本框内重现。但如果输入一个字，再按照你的方法，依然可以重现这个问题。不过这要求第一个字和删除 @ 之后输入的字正好是一个昵称。
- 00d15b2: WCompleteLineEdit: Fix may be undefined var: pos.
  
  其实这个问题的根源就是 `pos` 可能使用时是未定义的，而我之前的假设 pos 必然会被赋值。因此我把这个假设写成一个断言。
  
  然后再重现这个 Bug，原因就很明显了。

```
  ------------[ cut here ]------------

Version: WeCase 0.06-beta5-00d15b2

Traceback (most recent call last):
  File "/home/biergaizi/.local/lib64/python3.3/site-packages/WeCase/WCompleteLineEdit.py", line 94, in keyPressEvent
    self.listView.currentIndex().data())
  File "/home/biergaizi/.local/lib64/python3.3/site-packages/WeCase/WCompleteLineEdit.py", line 170, in getNewText
    assert pos != -1, "Cannot find self.mentionFlag."
AssertionError: Cannot find self.mentionFlag.
---[ end trace 0x7f30ee37ea70 ]---
```
