### ISSUE TITLE
启动之后点击其他微博用户头像出现错误

### ISSUE THREAD

**Issue by townboy** [WeCase/WeCase#127]
Oops, there is an unexpected error,
Please report it to http://bugs.wecase.org/
------------[ cut here ]------------

Version: WeCase 0.06-beta5-2456d12

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeHack.py", line 30, in run_with_except_hook
    run_old(_args, *_kw)
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 99, in _common_get
    timeline = timeline_func()
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 157, in timeline_get
    timeline = self.timeline.get(page=page, uid=self._uid).statuses
  File "/usr/local/lib/python3/dist-packages/WeCase/weibos/client.py", line 52, in __call__
    return super(_UBExecutable, self).__call__(*_kw)
  File "/usr/local/lib/python3.4/dist-packages/weibo3.py", line 291, in **call**
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, *_kw)
  File "/usr/local/lib/python3.4/dist-packages/weibo3.py", line 161, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo3.APIError: APIError: 21335: request uid's value must be the current user, request: /2/statuses/user_timeline.json
---[ end trace 0x7f4d21a096a8 ]---

![screenshot - 20140617 - 210507](https://cloud.githubusercontent.com/assets/4470181/3300874/66222286-f625-11e3-8f17-35512f47bd31.png)

**Comment by biergaizi** [comment]
这个问题已经重复被报告三次了。

**Comment by biergaizi** [comment]
详见 #119
