### ISSUE TITLE
TypeError: connection is not unique

### ISSUE THREAD

**Issue by senseab** [WeCase/WeCase#128]
```
root        : ERROR    苍天啊，大地啊！这个不明错误怎么就发生了呢，
请去 <http://bugs.wecase.org/> 报告该问题

------------[ cut here ]------------

Version: WeCase 0.06-beta7-77dde86-dirty

Traceback (most recent call last):
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 116, in _rowsInserted
    widget = SingleTweetWidget(item, self.without, self)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 192, in __init__
    self.setupUi()
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 309, in setupUi
    text = self._create_smiles(text)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 601, in _create_smiles
    self._create_animation(face.path)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 613, in _create_animation
    movie.frameChanged.connect(self.drawAnimate, QtCore.Qt.UniqueConnection)
TypeError: connection is not unique
---[ end trace 0x7f2276c2bd00 ]---
root        : ERROR    Same error...
Traceback (most recent call last):
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 116, in _rowsInserted
    widget = SingleTweetWidget(item, self.without, self)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 192, in __init__
    self.setupUi()
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 309, in setupUi
    text = self._create_smiles(text)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 601, in _create_smiles
    self._create_animation(face.path)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 613, in _create_animation
    movie.frameChanged.connect(self.drawAnimate, QtCore.Qt.UniqueConnection)
TypeError: connection is not unique
Traceback (most recent call last):
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 116, in _rowsInserted
    widget = SingleTweetWidget(item, self.without, self)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 192, in __init__
    self.setupUi()
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 309, in setupUi
    text = self._create_smiles(text)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 601, in _create_smiles
    self._create_animation(face.path)
  File "/opt/wecase/lib/python3.4/site-packages/WeCase/TweetListWidget.py", line 613, in _create_animation
    movie.frameChanged.connect(self.drawAnimate, QtCore.Qt.UniqueConnection)
TypeError: connection is not unique
```

**Comment by biergaizi** [comment]
```
TypeError: connection is not unique
```

天啊，新的 PyQt 居然连这个也吐槽。我知道了。

**Comment by biergaizi** [comment]
你可以把第二个参数 `QtCore.Qt.UniqueConnection` 去掉，即可恢复正常。完整的解决方法我稍后提交。
