### ISSUE TITLE
特定Unicode字符无法处理

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#129]
如题
当输入框中带有非常规Unicode如Emoji时无法处理

![screenshot from 2014-07-13 20 21 34](https://cloud.githubusercontent.com/assets/3353318/3564484/6b6f1e70-0a88-11e4-9d02-22f2d49964dd.png)

```
------------[ cut here ]------------

Version: WeCase 0.06-beta7-unknown

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeHack.py", line 30, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3/dist-packages/WeCase/NewpostWindow.py", line 167, in retweet
    self.tweet.retweet(text, comment, comment_ori)
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 688, in retweet
    is_comment=int(comment + comment_ori * 2))
  File "/usr/local/lib/python3/dist-packages/WeCase/weibos/client.py", line 62, in __call__
    return super(_UBExecutable, self).__call__(**kw)
  File "/usr/local/lib/python3.4/dist-packages/weibo3.py", line 308, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/local/lib/python3.4/dist-packages/weibo3.py", line 149, in _http_call
    params = _encode_params(**kw)
  File "/usr/local/lib/python3.4/dist-packages/weibo3.py", line 71, in _encode_params
    qv = v.encode() if isinstance(v, str) else v
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83d' in position 11: surrogates not allowed
---[ end trace 0xaf818d2c ]---
```

**Comment by biergaizi** [comment]
Emoji 使用了 Unicode 的私有造字区，的确有些棘手啊。

**Comment by cthbleachbit** [comment]
这个这个有解么。。。四次元没有这样的问题

**Comment by biergaizi** [comment]
有解。但你看到了，这个问题出在 SDK 上，而 SDK 的代码质量你也是知道的，我根本不想碰它。

我用新 SDK 替换这个 SDK 后问题就能自动解决了……

**Comment by biergaizi** [comment]
@cthbleachbit 你先找一段会导致异常的文本吧，我好用来当测试用例。

**Comment by cthbleachbit** [comment]
比如以下

😁😂

**Comment by biergaizi** [comment]
@cthbleachbit 无法重现……

**Comment by biergaizi** [comment]
本地无法重现此问题，请测试 rpweibo 分支有无此问题。

**Comment by biergaizi** [comment]
似乎此问题是错误转义成 UTF-16 或者被截断的 Emoji 造成的。如果能重现此问题，请 reopen.

**Comment by cthbleachbit** [comment]
仍然存在问题

**Comment by Garfield550** [comment]
是不是字体毛病

**Comment by Garfield550** [comment]
我这几天一直发 Emoji 表情

**Comment by cthbleachbit** [comment]
Emoji能显示出来，但是只要输入的内容包含Emoji就会发不出去

**Comment by Garfield550** [comment]
@cthbleachbit 网页版不也是么，转发不能发 Emoji

**Comment by cthbleachbit** [comment]
可以的

**Comment by Garfield550** [comment]
@cthbleachbit 似乎不可以啊

**Comment by cthbleachbit** [comment]
那是炸浪的bug，无视掉好了

**Comment by Garfield550** [comment]
@cthbleachbit 持续好多年了

**Comment by biergaizi** [comment]
啥叫好多年，渣浪微博才几年啊……

**Comment by Garfield550** [comment]
@biergaizi 有两年了吧。我玩微博已经 4年

**Comment by cthbleachbit** [comment]
@biergaizi 看样子是变成了被截断的Emoji

**Comment by biergaizi** [comment]
@cthbleachbit 请再次尝试重现问题并附带调用堆栈，以便解决此遗留问题。

**Comment by biergaizi** [comment]
如果能找到一个 100% 重现的字符串就好解决了。

**Comment by biergaizi** [comment]
初步确定问题是 urllib 的 quote 系列函数默认 `errors='strict'` 导致 `surrogates not allowed`，不过还是需要新的错误堆栈确定问题。
