### ISSUE TITLE
ImportError: No module named dateutil

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#13]
$ python3 ./wecase.py
Traceback (most recent call last):
  File "./src/wecase.py", line 16, in <module>
    from dateutil import parser as time_parser
ImportError: No module named dateutil

$ python2 ./wecase.py
Traceback (most recent call last):
  File "./src/wecase.py", line 16, in <module>
    from dateutil import parser as time_parser
ImportError: No module named dateutil

dateutil是什么？

**Comment by biergaizi** [comment]
自己去搜索

**Comment by Garfield550** [comment]
以解决
