### ISSUE TITLE
ValueError: read of closed file

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#131]
<code>
苍天啊，大地啊！这个不明错误怎么就发生了呢，
请去 http://bugs.wecase.org/ 报告该问题

------------[ cut here ]------------

Version: WeCase 0.06-beta7-7379b69

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/site-packages/WeCase/WeHack.py", line 30, in run_with_except_hook
    run_old(_args, *_kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python3.2/site-packages/WeCase/AsyncFetcher.py", line 65, in _download
    urlretrieve(url, filepath)
  File "/usr/lib/python3.2/urllib/request.py", line 151, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python3.2/urllib/request.py", line 1602, in retrieve
    block = fp.read(bs)
ValueError: read of closed file
---[ end trace 0x6fff2eb4e68 ]---
</code>

Bug 展示微博：http://weibo.com/1869586921/BfZR9za4C

**Comment by biergaizi** [comment]
是 duplicate，居然依然是 Issue #72

**Comment by biergaizi** [comment]
请移步讨论。
