### ISSUE TITLE
登录时没有捕获超时错误

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#137]
```
------------[ cut here ]------------

Version: WeCase 0.06-beta8-unknown

Traceback (most recent call last):
  File "/usr/share/wecase/WeHack.py", line 29, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib64/python3.3/threading.py", line 858, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/wecase/LoginWindow.py", line 138, in authorize
    weibo.auth(authenticator)
  File "/home/biergaizi/.local/lib64/python3.3/site-packages/rpweibo.py", line 147, in auth
    access_token = authenticator.auth(self.application)
  File "/home/biergaizi/.local/lib64/python3.3/site-packages/rpweibo.py", line 330, in auth
    return self._request_access_token(application, authorize_code)
  File "/home/biergaizi/.local/lib64/python3.3/site-packages/rpweibo.py", line 325, in _request_access_token
    result = curl.post(self.ACCESS_TOKEN_URL, access_token_parameter)
  File "/usr/lib64/python3.3/site-packages/curl/__init__.py", line 104, in post
    return self.__request(cgi)
  File "/home/biergaizi/.local/lib64/python3.3/site-packages/rpweibo.py", line 38, in __request
    super().__request(relative_url)
  File "/usr/lib64/python3.3/site-packages/curl/__init__.py", line 89, in __request
    self.handle.perform()
pycurl.error: (28, 'Operation timed out after 0 milliseconds with 0 out of 0 bytes received')
---[ end trace 0x7f04e40eaf58 ]---
```

**Comment by biergaizi** [comment]
Fixed in https://github.com/WeCase/rpweibo/commit/0970fe8598eb65be866198e6d5c903a96b79d6ce.
