### ISSUE TITLE
Why  db type could not be determined？

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#14]
$ python3 ./src/wecase.py
Traceback (most recent call last):
  File "./src/wecase.py", line 700, in <module>
    wecase_login = LoginWindow()
  File "./src/wecase.py", line 173, in **init**
    self.loadConfig()
  File "./src/wecase.py", line 200, in loadConfig
    self.config = shelve.open(config_path, 'c')
  File "/usr/lib/python3.2/shelve.py", line 232, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.2/shelve.py", line 216, in **init**
    Shelf.**init**(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.2/dbm/**init**.py", line 83, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined

**Comment by biergaizi** [comment]
rm -rf  ~/.config/wecase

**Comment by Garfield550** [comment]
看来要写个教程了~好多依赖要先安装……

**Comment by biergaizi** [comment]
这个是从旧版本升级过来才可能有的问题

**Comment by Garfield550** [comment]
嗯，

**Comment by Garfield550** [comment]
收藏好时，颜色为red最好

**Comment by Garfield550** [comment]
……

**Comment by biergaizi** [comment]
新浪虽然有提供微博是否被收藏的接口，但是它不工作，新浪表示没有启用的计划。也就是说没有任何办法判断微博是否被收藏。如果是把 Favorite 的图标改成 red 是可以的

**Comment by Garfield550** [comment]
只改成red就好
