### ISSUE TITLE
发送bmp图片出错

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#146]
如题，传送bmp图片时，发送失败并给出如下错误

```
Version: WeCase 0.06-beta7-unknown

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeiboErrorHandler.py", line 43, in showAPIException
    error_message = self.ERRORS[int(exception.error_code)]
KeyError: 20005

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeiboErrorHandler.py", line 45, in showAPIException
    error_message = "%d: %s" % (int(exception.error_code), exception.error)
AttributeError: 'CallerError' object has no attribute 'error'
---[ end trace 0xaeed468c ]---
```

**Comment by biergaizi** [comment]
渣浪 API 再次返回不可理喻的错误。然后暴露了错误捕获代码中的错误……

**Comment by biergaizi** [comment]
just a typo...
