### ISSUE TITLE
KeyError: 'access_token' 错误，无法登陆

### ISSUE THREAD

**Issue by allblue** [WeCase/WeCase#159]
ArchLinux下通过aur自动安装，安装过程中一切顺利，但是登陆时报KeyError: 'access_token'错误，请问是什么原因导致？
附错误信息

Version: WeCase 0.06-beta8-unknown

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/rpweibo.py", line 437, in _request_access_token
    return json.loads(result)["access_token"]
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/wecase/WeHack.py", line 29, in run_with_except_hook
    run_old(_args, *_kw)
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/share/wecase/LoginWindow.py", line 138, in authorize
    weibo.auth(authenticator)
  File "/usr/lib/python3.4/site-packages/rpweibo.py", line 167, in auth
    access_token = authenticator.auth(self.application)
  File "/usr/lib/python3.4/site-packages/rpweibo.py", line 443, in auth
    return self._request_access_token(application, authorize_code)
  File "/usr/lib/python3.4/site-packages/rpweibo.py", line 439, in _request_access_token
    raise AuthorizeError
rpweibo.AuthorizeError

**Comment by Garfield550** [comment]
请立即从 AUR 卸载该版本。

AUR 的版本使用的 Access Token 已经被废弃。

**Comment by cthbleachbit** [comment]
AUR 现在是谁在维护。。

Best Regards.
James Chai <F4657048>

**Comment by biergaizi** [comment]
没有人维护，最后一个维护者是我。
