### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#32]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 28: invalid start byte

我今天更改了字体～
@biergaizi 
@m13253

**Comment by m13253** [comment]
你能把行号给我么。。。
另外试试看用 `xxx.decode('utf-8', 'replace')` 来强制解码。

**Comment by Garfield550** [comment]
@m13253 
Traceback (most recent call last):
  File "./WeCase/src/wecase.py", line 814, in <module>
    wecase_login = LoginWindow()
  File "./WeCase/src/wecase.py", line 63, in **init**
    self.loadConfig()
  File "./WeCase/src/wecase.py", line 110, in loadConfig
    self.config.read(config_path)
  File "/usr/lib/python3.2/configparser.py", line 689, in read
    self._read(fp, filename)
  File "/usr/lib/python3.2/configparser.py", line 994, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.2/codecs.py", line 300, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 28: invalid start byte

**Comment by m13253** [comment]
哦。升级到 0.0.3 之后配置文件格式变化了。
请清空配置文件 `~/.config/wecase`

**Comment by Garfield550** [comment]
哦

**Comment by m13253** [comment]
如果你解决了，请自行 Close this thread

**Comment by biergaizi** [comment]
此 bug 标记为 invalid。
