### ISSUE TITLE
打不开的说。。。

### ISSUE THREAD

**Issue by 2q1w2007** [WeCase/WeCase#43]
Traceback (most recent call last):
  File "./src/wecase.py", line 12, in <module>
    from LoginWindow import LoginWindow
  File "/home/ha2q1w2007/WeCase/src/LoginWindow.py", line 21, in <module>
    from WeCaseWindow import WeCaseWindow
  File "/home/ha2q1w2007/WeCase/src/WeCaseWindow.py", line 19, in <module>
    from Notify import Notify
  File "/home/ha2q1w2007/WeCase/src/Notify.py", line 10, in <module>
    import notify2 as pynotify
ImportError: No module named notify2

**Comment by Garfield550** [comment]
你需要安装Notify

**Comment by Garfield550** [comment]
请在安装前仔细阅读Readme
https://github.com/WeCase/WeCase
