### ISSUE TITLE
当进入@我之后，点击刷新就会报错。错误报告如下

### ISSUE THREAD

**Issue by classstudios** [WeCase/WeCase#46]
```
Oops, there is an unexcepted error: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/weibo.py", line 142, in _http_call
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.3/urllib/request.py", line 160, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.3/urllib/request.py", line 479, in open
    response = meth(req, response)
  File "/usr/lib/python3.3/urllib/request.py", line 591, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.3/urllib/request.py", line 517, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.3/urllib/request.py", line 451, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/urllib/request.py", line 599, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/home/WeCase/src/WeCaseWindow.py", line 186, in refresh
    self.reset_remind()
  File "/home/home/WeCase/src/WeCaseWindow.py", line 95, in reset_remind
    self.client.remind.set_count.post(type="mention_status")
  File "/usr/local/lib/python3.3/dist-packages/weibo.py", line 276, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/local/lib/python3.3/dist-packages/weibo.py", line 154, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo.APIError: APIError: 21320: unsupport_protocol, request: /2/remind/set_count.json

Please report it at https://github.com/WeCase/WeCase/issues
```

**Comment by cthbleachbit** [comment]
我的没有出现这样的问题啊，，还记得在此之前你有做什么吗

**Comment by classstudios** [comment]
好像没有把。另外点击我按钮。有什么功能吗？好像没有啥反应。如果可以做成Launcher就好了。不用每次都要到源文件里运行。

------------------ 原始邮件 ------------------
发件人: "cthbleachbit"notifications@github.com;
发送时间: 2013年6月19日(星期三) 中午1:39
收件人: "WeCase/WeCase"WeCase@noreply.github.com; 
抄送: "段段"1036198123@qq.com; 
主题: Re: [WeCase] 当进入@我之后，点击刷新就会报错。错误报告如下 (#46)

我的没有出现这样的问题啊，，还记得在此之前你有做什么吗

**Comment by cthbleachbit** [comment]
没有啥反应的意思是你现在没有新的at消息，，，launcher的话要配合安装使用，，待以后有了安装脚本就可以有launcher了，

**Comment by biergaizi** [comment]
纯属网络问题。而且原因无法复现。
新浪的 API 相当不稳定，我正在尝试添加一些错误处理。

另外，你使用的是原版的 WeCase，还是某个发行版的？

**Comment by biergaizi** [comment]
@duanduanduan “我”按钮很快就会被删除，根本没用。

**Comment by classstudios** [comment]
GitHub 上的。用源代码make的。

------------------ 原始邮件 ------------------
发件人: "Tom Li"; 
发送时间: 2013年6月19日(星期三) 晚上6:06
收件人: "WeCase/WeCase"; 
抄送: "段段"1036198123@qq.com; 
主题: Re: [WeCase] 当进入@我之后，点击刷新就会报错。错误报告如下 (#46)

纯属网络问题。而且原因无法复现。
 新浪的 API 相当不稳定，我正在尝试添加一些错误处理。

另外，你使用的是原版的 WeCase，还是某个发行版的？

&mdash;

**Comment by cthbleachbit** [comment]
Make?.?.

By CTH via iPad

**Comment by classstudios** [comment]
抱歉，我的意思是说就是git 下来的然后install 的。

**Comment by classstudios** [comment]
确实是网络问题。换一个地方就没事。可能是weiboAPI的服务器的问题。

**Comment by biergaizi** [comment]
嗯，渣浪的 API 相当没谱，我都要崩溃了。
