### ISSUE TITLE
Wrapped C/C++ object of type QLabel has been deleted

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#49]
```
Oops, there is an unexcepted error: 

Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 271, in _update_time
    self.time.setText("<a href='%s'>%s</a>" % (self.tweet.url, self.tweet.time))
RuntimeError: wrapped C/C++ object of type QLabel has been deleted

Please report it at https://github.com/WeCase/WeCase/issues
```

**Comment by biergaizi** [comment]
嗯，这是一个已知问题，但是难以复现，更难调试。这是一个多线程和垃圾收集联手造成的问题。

**Comment by biergaizi** [comment]
我这里又发生了一次，不过实在难以重现啊……

```
Traceback (most recent call last):
  File "/home/biergaizi/WeCase.commit/src/TweetListWidget.py", line 271, in _update_time
    self.time.setText("<a href='%s'>%s</a>" % (self.tweet.url, self.tweet.time))
RuntimeError: wrapped C/C++ object of type QLabel has been deleted
```

**Comment by biergaizi** [comment]
Fixed in 98aac1d.

**Comment by biergaizi** [comment]
这个 Bug 并没有被真正修复，我又尝试了一些修正，希望在第二个 Beta 版中得到确认。

**Comment by biergaizi** [comment]
终于搞定了。

**Comment by biergaizi** [comment]
通过标记 `pyqtSlot` 这个问题应该已经彻底解决。
