### ISSUE TITLE
不能正确处理已经被删掉的微博

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#52]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/weibo.py", line 142, in _http_call
    resp = urllib.request.urlopen(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/usr/lib64/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 595, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biergaizi/WeCase.commit/src/TweetListWidget.py", line 427, in _retweet
    wecase_new = NewpostWindow("retweet", tweet)
  File "/home/biergaizi/WeCase.commit/src/NewpostWindow.py", line 31, in __init__
    self.setupUi(self)
  File "/home/biergaizi/WeCase.commit/src/NewpostWindow.py", line 41, in setupUi
    self._create_tweetWidget()
  File "/home/biergaizi/WeCase.commit/src/NewpostWindow.py", line 81, in _create_tweetWidget
    self.tweet.refresh()
  File "/home/biergaizi/WeCase.commit/src/Tweet.py", line 408, in refresh
    self._data = self.client.statuses.show.get(id=self.id)
  File "/usr/lib64/python3.3/site-packages/weibo.py", line 276, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/lib64/python3.3/site-packages/weibo.py", line 154, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo.APIError: APIError: 20101: target weibo does not exist!, request: /2/statuses/show.json
```

**Comment by biergaizi** [comment]
Fixed in 53391a1.
