### ISSUE TITLE
点击转发时出错

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#64]
转发窗口打开后立即自动关闭

弹出两段错误

```
Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 106, in _rowsInserted
    self.setBusy(False, self.TOP)
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 142, in setBusy
    self._setTopBusy(busy)
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 151, in _setTopBusy
    elif not busy and self.busy() == self.TOP:
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 125, in busy
    top_widget = self.layout.itemAt(0)
RuntimeError: wrapped C/C++ object of type QVBoxLayout has been deleted
```

还有

```
Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 110, in _rowsInserted
    widget = SingleTweetWidget(item, self.without, self)
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 180, in __init__
    self.setupUi()
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 257, in setupUi
    self.favorite = self._createFavoriteLabel()
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 401, in _createFavoriteLabel
    favorite = WIconLabel(self)
  File "/home/cth451/文档/git/WeCase/src/WIconLabel.py", line 21, in __init__
    super(WIconLabel, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type SingleTweetWidget has been deleted
```

**Comment by biergaizi** [comment]
难怪凌晨我感觉不太正常呢，原来被垃圾回收了……

**Comment by biergaizi** [comment]
Fixed in 0a3ca1f23c1e8c50311f7c7ff408ded10e4b1118.
