### ISSUE TITLE
打开的文件过多

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#69]
```
Oops, there is an unexpected error: 

Traceback (most recent call last):
  File "/usr/lib/python3.3/urllib/request.py", line 1252, in do_open
  File "/usr/lib/python3.3/http/client.py", line 1061, in request
  File "/usr/lib/python3.3/http/client.py", line 1099, in _send_request
  File "/usr/lib/python3.3/http/client.py", line 1057, in endheaders
  File "/usr/lib/python3.3/http/client.py", line 902, in _send_output
  File "/usr/lib/python3.3/http/client.py", line 840, in send
  File "/usr/lib/python3.3/http/client.py", line 1194, in connect
  File "/usr/lib/python3.3/socket.py", line 417, in create_connection
OSError: [Errno 24] 打开的文件过多

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/WeHack.py", line 17, in run_with_except_hook
  File "/home/cth451/文档/git/WeCase/src/WTimer.py", line 24, in run
  File "/home/cth451/文档/git/WeCase/src/WeCaseWindow.py", line 339, in show_notify
  File "/home/cth451/文档/git/WeCase/src/WeCaseWindow.py", line 320, in get_remind
  File "/usr/local/lib/python3.3/dist-packages/weibo.py", line 276, in __call__
  File "/usr/local/lib/python3.3/dist-packages/weibo.py", line 142, in _http_call
  File "/usr/lib/python3.3/urllib/request.py", line 160, in urlopen
  File "/usr/lib/python3.3/urllib/request.py", line 473, in open
  File "/usr/lib/python3.3/urllib/request.py", line 491, in _open
  File "/usr/lib/python3.3/urllib/request.py", line 451, in _call_chain
  File "/usr/lib/python3.3/urllib/request.py", line 1287, in https_open
  File "/usr/lib/python3.3/urllib/request.py", line 1255, in do_open
urllib.error.URLError: <urlopen error [Errno 24] 打开的文件过多>

Please report it at https://github.com/WeCase/WeCase/issues
```

**Comment by biergaizi** [comment]
纳尼……

**Comment by biergaizi** [comment]
下次遇到此问题，请保持 WeCase 运行，使用 `lsof` 命令查看 WeCase 究竟打开了什么文件。

`lsof`用法请参考 man page.

**Comment by cthbleachbit** [comment]
ok

**Comment by biergaizi** [comment]
暂时发现打开的 `busy.gif` 有点多了……

```
➜  ~  lsof -p 25809  | grep busy.gif | wc -l
138
➜  ~  lsof -p 25809  | grep busy.gif | wc -l
138
➜  ~  lsof -p 25809  | grep busy.gif | wc -l
169
➜  ~  lsof -p 25809  | grep busy.gif | wc -l
200
➜  ~  lsof -p 25809  | grep busy.gif | wc -l
234
➜  ~  
```

**Comment by biergaizi** [comment]
做了些初步修正：https://github.com/WeCase/WeCase/commit/ebec59e70b6c571c86574b4e7f17eaadedf58c3f 和 https://github.com/WeCase/WeCase/commit/53c8383194ef28e73bc09640de56c2b20c141860

**Comment by biergaizi** [comment]
@cthbleachbit 另外我需要知道，你的系统默认允许打开多少文件。运行 `cat /proc/sys/fs/file-max` 告诉我结果。

**Comment by biergaizi** [comment]
又做了 https://github.com/WeCase/WeCase/commit/31e66ae16a9ec3c0d79c11843de7247a90cb6cb2 修正，这下总不会打开这么多文件了。

另外 IRC 上问得 Ubuntu 10.04.4 LTS 的 `file-max` 是 11207，总不可能打开这么多文件了。

**Comment by cthbleachbit** [comment]
202273，，
