### ISSUE TITLE
TypeError: pyqtSignal must be bound to a QObject / DBus Issue

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#70]
```
Traceback (most recent call last):
  File "/home/li/WeCase/src/WeHack.py", line 17, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/li/WeCase/src/WAsyncLabel.py", line 169, in fetch
    self.down(url, filename)
  File "/home/li/WeCase/src/WAsyncLabel.py", line 159, in down
    self.fetched.emit(down_path + filename)
TypeError: pyqtSignal must be bound to a QObject, not 'WAsyncFetcher'
```

**Comment by Garfield550** [comment]
这些错误是登录之后出现的
[第一个](https://github.com/WeCase/WeCase/issues/72)是注销再登录出现
第二个（这个）是首次启动，登录出现
_重复请关闭_

**Comment by cthbleachbit** [comment]
Hack的问题真多。。

**Comment by Garfield550** [comment]
# 你刚刚说完，就……

Traceback (most recent call last):
  File "/home/li/WeCase/src/WeHack.py", line 17, in run_with_except_hook
    run_old(_args, *_kw)
  File "/home/li/WeCase/src/WTimer.py", line 24, in run
    self.run_function()
  File "/home/li/WeCase/src/WeCaseWindow.py", line 365, in show_notify
    self.notify.showMessage(self.tr("WeCase"), msg)
  File "/home/li/WeCase/src/Notify.py", line 30, in showMessage
    self.n.show()
  File "/usr/lib/python3/dist-packages/notify2.py", line 188, in show
    self.timeout,  # expire_timeout
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in **call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.25 was not provided by any .service files

**Comment by cthbleachbit** [comment]
Oh gosh...

**Comment by biergaizi** [comment]
@Garfield550 你这个是 Linux 系统的问题。

**Comment by Garfield550** [comment]
@biergaizi 那求解，我更新过系统了

**Comment by biergaizi** [comment]
@cthbleachbit 这个问题产生的原因很简单，和你说的复杂情况无关。

这个问题产生的原因是，一个窗口正在使用 `WAsyncFetcher` 加载文件，还没加载完就被关闭了。这时候 `WAsyncFetcher` 仍然在运行，但 self 已经被垃圾回收了，不再是一个 `QObject` 因此出现类型不对的问题。

我在开发草稿中描述了类似问题。

**Comment by Garfield550** [comment]
@biergaizi 剩下那两个呢

**Comment by cthbleachbit** [comment]
Get

**Comment by biergaizi** [comment]
@Garfield550 你的 dbus 不工作了，重启一下。另，不要在一个 Bug 里报告另一个 Bug。

**Comment by Garfield550** [comment]
@biergaizi 好的，我注意。重启dbus？

**Comment by biergaizi** [comment]
@Garfield550 这个问题还和 DBus 的通知后端有关系。就是你桌面环境使用的 `notify-daemon`。

你需要重启 DBus 再重登录一下看看。

**Comment by Garfield550** [comment]
@biergaizi 嗯，好

暂时没事了

**Comment by biergaizi** [comment]
已经拆分此 Bug。
