### ISSUE TITLE
文件没找到？？

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#75]
```
Oops, there is an unexpected error: 

Traceback (most recent call last):
  File "/usr/lib/python3.3/urllib/request.py", line 1252, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.3/http/client.py", line 1061, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.3/http/client.py", line 1099, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.3/http/client.py", line 1057, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.3/http/client.py", line 902, in _send_output
    self.send(msg)
  File "/usr/lib/python3.3/http/client.py", line 840, in send
    self.connect()
  File "/usr/lib/python3.3/http/client.py", line 1194, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.3/socket.py", line 417, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
FileNotFoundError: [Errno 2] 没有那个文件或目录

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/WeHack.py", line 17, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/cth451/文档/git/WeCase/src/WTimer.py", line 24, in run
    self.run_function()
  File "/home/cth451/文档/git/WeCase/src/WeCaseWindow.py", line 361, in show_notify
    reminds = self.get_remind(self.uid())
  File "/home/cth451/文档/git/WeCase/src/WeCaseWindow.py", line 342, in get_remind
    reminds = self.client.remind.unread_count.get(uid=uid)
  File "/usr/local/lib/python3.3/dist-packages/weibo.py", line 276, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/local/lib/python3.3/dist-packages/weibo.py", line 142, in _http_call
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.3/urllib/request.py", line 160, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.3/urllib/request.py", line 473, in open
    response = self._open(req, data)
  File "/usr/lib/python3.3/urllib/request.py", line 491, in _open
    '_open', req)
  File "/usr/lib/python3.3/urllib/request.py", line 451, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/urllib/request.py", line 1287, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.3/urllib/request.py", line 1255, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] 没有那个文件或目录>

Please report it at https://github.com/WeCase/WeCase/issues
```

**Comment by biergaizi** [comment]
找不到套接字……

**Comment by biergaizi** [comment]
又是网络问题

**Comment by biergaizi** [comment]
其实归根结底，最后抛出的是 `urllib.error.URLError`，捕获一下就好。
