### ISSUE TITLE
登录过程超时并报错

### ISSUE THREAD

**Issue by m13253** [WeCase/WeCase#80]
登录过程超时并报错如下：
另建议把“请去xxx报告问题挪动到第二行”。

```
苍天啊，大地啊！这个不明错误怎么就发生了呢：

Traceback (most recent call last):
  File "/usr/lib/WeCase/src/LoginWindow.py", line 79, in checkLogin
    self.accept()
  File "/usr/lib/WeCase/src/LoginWindow.py", line 49, in accept
    wecase_main = WeCaseWindow()
  File "/usr/lib/WeCase/src/WeCaseWindow.py", line 55, in __init__
    self.init_account()
  File "/usr/lib/WeCase/src/WeCaseWindow.py", line 352, in init_account
    self.uid()
  File "/usr/lib/WeCase/src/WeCaseWindow.py", line 424, in uid
    self.info["uid"] = self.client.account.get_uid.get().uid
  File "/usr/lib/WeCase/src/weibo.py", line 276, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/lib/WeCase/src/weibo.py", line 142, in _http_call
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/lib/python3.3/urllib/request.py", line 487, in _open
    '_open', req)
  File "/usr/lib/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.3/urllib/request.py", line 1253, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.3/http/client.py", line 1143, in getresponse
    response.begin()
  File "/usr/lib/python3.3/http/client.py", line 354, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.3/http/client.py", line 324, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

请去 https://github.com/WeCase/WeCase/issues 报告该问题
```

**Comment by biergaizi** [comment]
嗯，又是 `BadStatusLine` 嘛，我知道了。

建议会采纳。

**Comment by biergaizi** [comment]
Fixed in 8cddd91.

建议在 a20d912 采纳。
