### ISSUE TITLE
转发按钮错误

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#85]
```
Traceback (most recent call last):
  File "/home/cth451/文档/WeCase/src/WCompleteLineEdit.py", line 60, in focusOutEvent
    self.listView.hide()
AttributeError: 'WCompleteLineEdit' object has no attribute 'listView'
```

这个错误是在我U盘精简版系统上发生的，是否和这个有关？

**Comment by biergaizi** [comment]
真是太奇怪了……

**Comment by biergaizi** [comment]
完全不可能发生……能重现吗？

**Comment by cthbleachbit** [comment]
因为我是在我的U盘上安装了Ubuntu，可能和U盘读取不给力有关，我现在在学校，明天去机房试试，
Cth 发自 iCloud

On Sep 21, 2013, at 09:23 PM, Tom Li notifications@github.com wrote:

几乎不可能发生……能重现吗？

**Comment by cthbleachbit** [comment]
貌似没有重现，应该是I/O速度过慢导致加载失败造成的

**Comment by cthbleachbit** [comment]
重现了！！貌似是在连续点击转发之后会重现，

**Comment by biergaizi** [comment]
重现步骤麻烦给详细点……

**Comment by cthbleachbit** [comment]
找到任意一条转发数不为0的微博，连续点击两次转发按钮，有几率重现

**Comment by cthbleachbit** [comment]
我刚刚卡bug的时候出现了不同的信息。。。。

```
Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 104, in _rowsInserted
    widget = SingleTweetWidget(item, self.without, self)
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 177, in __init__
    self.setupUi()
  File "/home/cth451/文档/git/WeCase/src/TweetListWidget.py", line 221, in setupUi
    self.username = QtGui.QLabel(self)
RuntimeError: underlying C/C++ object has been deleted
```

**Comment by biergaizi** [comment]
@cthbleachbit 这是一个已知问题，和这个 Bug 没有任何关系，属于不相关报告，违规，应该避免。在 `DRAFT.md` 里记载。

>  点击一条微博评论/转发按钮时，评论和转发信息就会开始异步加载并构建界面。如果网络延迟较高或迅速关闭窗口，可能加载仍在进行中。构建界面时，由于窗口对象早就不存在了，会出现 RuntimeError 异常，暂时没有合理的解决方案。在很多场景下都有类似的问题。

**Comment by cthbleachbit** [comment]
......all right...

By CTH via iPad

**Comment by biergaizi** [comment]
好了，那就算这个 Bug 解决了。

Fixed in 936b11ff9b458fff485d6acb688584390ce80c9b.
