### ISSUE TITLE
发超大图片时错误

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#86]
在处理micromacer的
![2013-10-02 21 12 37](https://f.cloud.github.com/assets/3353318/1253455/64c9d780-2b64-11e3-9933-1a5a1d8bf0b4.png)
，上传网页截图时出现错误，同时发送失败

已使用同一张图片多次重现

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/weibo.py", line 142, in _http_call
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.2/urllib/request.py", line 138, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 375, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 487, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 413, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 495, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/NewpostWindow.py", line 198, in new
    pic=open(self.image, "rb"))
  File "/home/cth451/文档/git/WeCase/src/weibos/client.py", line 40, in __call__
    return super(_UBExecutable, self).__call__(**kw)
  File "/usr/local/lib/python3.2/dist-packages/weibo.py", line 276, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/local/lib/python3.2/dist-packages/weibo.py", line 154, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo.APIError: APIError: 20006: image size too large., request: /2/statuses/upload.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/WeHack.py", line 20, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cth451/文档/git/WeCase/src/NewpostWindow.py", line 199, in new
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by biergaizi** [comment]
WTF，居然 `FileNotFoundError` 有的 Python 不支持……

**Comment by biergaizi** [comment]
另外这个错误是因为我没有捕获 `image size too large`

**Comment by cthbleachbit** [comment]
但在微博网页版上面是能够正常上传的

**Comment by biergaizi** [comment]
增加了一些错误检测代码，你再试试。

**Comment by cthbleachbit** [comment]
上次那张图删掉了，你说你让我去哪找，，，，不久测试

**Comment by biergaizi** [comment]
@cthbleachbit 赶紧找张大图帮我测试下，谢了……

**Comment by cthbleachbit** [comment]
貌似已经不是大图的问题哦了。。。

```
Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/src/WeHack.py", line 20, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cth451/文档/git/WeCase/src/NewpostWindow.py", line 200, in new
    if getsize > const.MAX_IMAGE_BYTES:
TypeError: unorderable types: function() > int()
```

**Comment by cthbleachbit** [comment]
但是图可以发出去

**Comment by biergaizi** [comment]
应该彻底修复了，你再试试。
