### ISSUE TITLE
~/.cache/wecase/ 不存在时报错

### ISSUE THREAD

**Issue by m13253** [WeCase/WeCase#88]
```
Traceback (most recent call last):
  File "/usr/lib/WeCase/src/wecase.py", line 102, in <module>
    setup_logger()
  File "/usr/lib/WeCase/src/wecase.py", line 93, in setup_logger
    filename=const.cache_path + "log")
  File "/usr/lib/python3.3/logging/__init__.py", line 1699, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.3/logging/__init__.py", line 966, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.3/logging/__init__.py", line 988, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/brilliant/.cache/wecase/log'
```

手工创建 `~/.cache/wecase/` 目录后运行成功。

WeCase 版本 4fb261232dd6732606057b5c7e7f8d272f9784c1 (master 分支最新版)

**Comment by biergaizi** [comment]
这就是 Beta 3.1 存在的原因，但好像我推送版本的时候存在问题，根本没有发布出去……

等下一个版本发布，它自己就好了。

**Comment by biergaizi** [comment]
Duplicate of #77.
