### ISSUE TITLE
为什么用GitHub for Windows Clone之后还是报错？

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#93]
<pre><code>
Oops, there is an unexpected error:

Traceback (most recent call last):
  File "C:\Users\Li\Documents\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 118, in _rowsInserted
    widget = SingleTweetWidget(item, self.without, self)
  File "C:\Users\Li\Documents\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 191, in __init__
    self.setupUi()
  File "C:\Users\Li\Documents\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 253, in setupUi
    self.originalLabel = self._createOriginalLabel()
  File "C:\Users\Li\Documents\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 359, in _createOriginalLabel
    text = self._create_smiles(text)
  File "C:\Users\Li\Documents\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 601, in _create_smiles
    faceModel.init()
  File "C:\Users\Li\Documents\WeCase-0.06-beta3.1\src\Face.py", line 88, in init
    self.__tree = ET.ElementTree(file=const.face_path + "./face.xml")
  File "C:\Python33\lib\xml\etree\ElementTree.py", line 620, in __init__
    self.parse(file)
  File "C:\Python33\lib\xml\etree\ElementTree.py", line 1718, in parse
    source = open(source, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Li\\Documents\\WeCase-0.06-beta3.1\\src/ui/img/face/./face.xml'

Please report it at https://github.com/WeCase/WeCase/issues
</code></pre>

![1](https://f.cloud.github.com/assets/3471836/1415746/9e501dd2-3f1b-11e3-8cd5-0fe9f2c7359b.PNG)
![2](https://f.cloud.github.com/assets/3471836/1415747/ab65a410-3f1b-11e3-9d03-f5432fc8fff2.PNG)

**Comment by Garfield550** [comment]
手动将src目录下ui文件删除并且将res目录下文件拷贝至src目录解决

**Comment by biergaizi** [comment]
因为 Windows 不支持符号链接，Roadmap（别找了，我没写，在我大脑里）里计划对其进行变通，所以不算 Bug。

**Comment by Garfield550** [comment]
∴我选了question
----- 原始邮件 -----
发件人：Tom Li notifications@github.com
收件人：WeCase/WeCase WeCase@noreply.github.com
抄送人：Garfield550 garfield_550@sina.cn
主题：Re:_[WeCase]_为什么用GitHub_for_Windows_Clone之后还是报错？_(#93)
日期：2013年10月28日 21点13分
