### ISSUE TITLE
windows xp下出现Unknown Error.版本WeCase-0.06-beta3.1

### ISSUE THREAD

**Issue by maijver** [WeCase/WeCase#94]
Oops, there is an unexpected error:

Traceback (most recent call last):
  File "C:\WeCase-0.06-beta3.1\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 118, in _rowsInserted
    widget = SingleTweetWidget(item, self.without, self)
  File "C:\WeCase-0.06-beta3.1\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 191, in __init__
    self.setupUi()
  File "C:\WeCase-0.06-beta3.1\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 301, in setupUi
    text = self._create_smiles(text)
  File "C:\WeCase-0.06-beta3.1\WeCase-0.06-beta3.1\src\TweetListWidget.py", line 601, in _create_smiles
    faceModel.init()
  File "C:\WeCase-0.06-beta3.1\WeCase-0.06-beta3.1\src\Face.py", line 88, in init
    self.__tree = ET.ElementTree(file=const.face_path + "./face.xml")
  File "C:\Python33\lib\xml\etree\ElementTree.py", line 620, in __init__
    self.parse(file)
  File "C:\Python33\lib\xml\etree\ElementTree.py", line 1718, in parse
    source = open(source, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\WeCase-0.06-beta3.1\WeCase-0.06-beta3.1\src/ui/img/face/./face.xml'

**Comment by biergaizi** [comment]
这个 Bug 是 7d6ce722fe66ef88cfcc3e051661b059b8ef2d5d （十月二日）修复的，将包括在下一步版本中。
