### ISSUE TITLE
刷新评论出错

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#98]
```
Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/release/WeHack.py", line 20, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cth451/文档/git/WeCase/release/Tweet.py", line 102, in _common_get
    timeline = timeline_func()
  File "/home/cth451/文档/git/WeCase/release/Tweet.py", line 182, in timeline_new
    timeline = self.timeline.get(since_id=self.first_id()).comments[::-1]
  File "/home/cth451/文档/git/WeCase/release/Tweet.py", line 83, in first_id
    assert self._tweets
AssertionError
```

**Comment by biergaizi** [comment]
百年不遇的 Bug 终于出现！这个 assert 就是为了等待它的！

**Comment by biergaizi** [comment]
A Good Catch！

**Comment by cthbleachbit** [comment]
......有Solution没

On Dec 31, 2013, at 11:52 PM, Tom Li notifications@github.com wrote:

A Good Catch！

**Comment by biergaizi** [comment]
这是逻辑上不可能，但偏偏发生了……

**Comment by biergaizi** [comment]
也许修好了。反正也没办法重现……

**Comment by Garfield550** [comment]
2333
