### ISSUE TITLE
刷话题时出错

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#99]
```
Traceback (most recent call last):
  File "/home/cth451/文档/git/WeCase/release/WeHack.py", line 20, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cth451/文档/git/WeCase/release/Tweet.py", line 110, in _common_get
    self.insertRows(pos, timeline)
  File "/home/cth451/文档/git/WeCase/release/Tweet.py", line 53, in insertRows
    self.beginInsertRows(QtCore.QModelIndex(), row, row + len(items) - 1)
TypeError: object of type 'list_reverseiterator' has no len()
```

能多次重现
且话题里的所有微博都无法显示图片

**Comment by biergaizi** [comment]
给一个能重现的话题名？

**Comment by cthbleachbit** [comment]
首屏Again

**Comment by cthbleachbit** [comment]
啊还有 Sherlock

**Comment by biergaizi** [comment]
能 100% 重现吗？难不成是 Python 3.2 故有的限制……

**Comment by cthbleachbit** [comment]
目测是的，对于所有话题都会这样。。

**Comment by biergaizi** [comment]
恩，看来是 Python 3.2 的反向迭代器不支持求长度，回头改改……

**Comment by biergaizi** [comment]
Fixed in f443a3b.

**Comment by biergaizi** [comment]
至于图片的问题，如果依然存在，请另开一个 Issue。
